### ISSUE TITLE
Credentials are not automatically saved after builtin mimikatz dumps for Mythic 3.0.0

### ISSUE THREAD

**Issue by lsecqt** [its-a-feature/Mythic#289]
When testing Mythic I performed 
* DCSync
![image](https://github.com/its-a-feature/Mythic/assets/102690672/26361844-6fe8-42ec-bd58-c4a76fa61816)
* SAM dump
![image](https://github.com/its-a-feature/Mythic/assets/102690672/f931bba7-f525-461c-a43b-9635da073ee5)
* Logonpasswords dump 
![image](https://github.com/its-a-feature/Mythic/assets/102690672/5152fb90-818e-40a6-ab5f-497da3d8d8b1)

None of the captured hashes was saved on credentials tab
![image](https://github.com/its-a-feature/Mythic/assets/102690672/4d175cdc-bbcb-463c-bf2a-a9ffdd2e91de)
![image](https://github.com/its-a-feature/Mythic/assets/102690672/9c299538-073b-45a0-9754-6710e167184d)

I used the latest [Apollo](https://github.com/MythicAgents/Apollo) during testing.

**Comment by its-a-feature** [comment]
Good catch! Turned out to be an issue with the `mythic-container` PyPi package that, when searching previous responses from tasking, wasn't returning strings, but rather byte strings. The PyPi package was updated to `v0.2.8rc04` for this and, once the pipeline finishes building the `mythic_python_dotnet` image (https://github.com/MythicMeta/Mythic_Docker_Templates/actions/runs/5008950633), then you'll be good to go to run `./mythic-cli build apollo` and try again

**Comment by its-a-feature** [comment]
Everything should be working now, can you verify?

**Comment by lsecqt** [comment]
I updated Mythic by git pull and still do not receive any creds. Do I need to reinstall it?

**Comment by its-a-feature** [comment]
Ah, it's not a Mythic issue, it's an Apollo container issue. So do:
```
./mythic-cli build apollo
```

**Comment by lsecqt** [comment]
Do I need to pull the agent separately?
I did
```
./mythic-cli build apollo
./mythic-cli restart
```

But still the same result.

P.S I recreated apollo binary and connected new hosts to be sure I am using the right one.

**Comment by its-a-feature** [comment]
it should have pulled in the latest with that build. The current Apollo scraper for Mimikatz is only looking for plaintext credentials though - are you getting plaintext credentials in your output?

**Comment by lsecqt** [comment]
No, only NTLM. That is strange tho, since I was getting NTLM hashes as well on previous versions.

**Comment by its-a-feature** [comment]
Oh really? 🤔 Even back in the 2.3 code it had https://github.com/MythicAgents/Apollo/blob/07c2efa9849cb139329460caae82ba02d6911456/Payload_Type/apollo/mythic/agent_functions/mimikatz.py#L83 to just look for `password != (null)`. Must have been a while ago that was change...

**Comment by lsecqt** [comment]
I have Apollo version 2.2.1 that counts NTLM hashes as plaintext. Perhaps something differs in the RPC calls in https://github.com/MythicAgents/Apollo/blob/478b7967824808af423a5e284bf77293fa4c51a7/Payload_Type/apollo/apollo/mythic/agent_functions/mimikatz.py#LL49C43-L49C72?

**Comment by lsecqt** [comment]
Update, I think I found the issue. I tried to replicate the python code for parsing the output. I am assuming that by passing "\r" the output is not parsed successfully. In my case everything is counted as a single line as long as "\r" is present:
![image](https://github.com/its-a-feature/Mythic/assets/102690672/cc0457ea-203a-4e91-a607-eed638f2a307)

In my sample code, modifying the filter to only "\n" fixed the issue:
![image](https://github.com/its-a-feature/Mythic/assets/102690672/1590a3dd-74bf-4450-a8f8-366bfd2f0bfa)

Can you verify if that is the case?

**Comment by its-a-feature** [comment]
I just tested how it normally is and it worked for me (plaintext and hashes - both reported as plaintext, but at least both recorded in Mythic). The output does have `\r\n` - for any given task, you can click the blue plus sign then click to "Download Output". If you do that for the output of your mimikatz command, you can look at it and see the `0d0a` which is the `\r\n` in the output.
![image](https://github.com/its-a-feature/Mythic/assets/5313261/b9b66e0a-ea18-4fb2-abbd-369940276cc3)

**Comment by lsecqt** [comment]
What apollo version you are using? I still cant reproduce successful result.

**Comment by its-a-feature** [comment]
I'm using the latest version on GitHub with the latest Mythic - I'm seeing both plaintext credentials and hashes show up in the credential store. My Apollo is running on a win10 box

**Comment by its-a-feature** [comment]
I did a fresh install and test last week with Apollo and saw credentials and hashes appear in the credential store for Mythic. I'm gonna close this for now and if you're still unable to see this with the latest Mythic and Apollo, then I'd need you to look at this section of code (https://github.com/MythicAgents/Apollo/blob/master/Payload_Type/apollo/apollo/mythic/agent_functions/mimikatz.py#L36-L60). This is where the Mythic side of Apollo is processing the mimikatz results and looking for credentials. Any change you make there you can load up by doing `./mythic-cli start apollo` and you can debug output with:
```
from mythic_container.logging import logger
logger.info("some data")
```
That'll help track down if there's a bug in Mythic/Apollo or if there's something with the data you're getting back that's just not matching the parsing that's happening. The current code is just labeling _everything_ has plaintext, even if it's a hash, so that's definitely something that can be updated
